name: solar system workflow 

on: 
 workflow_dispatch
 push:
  branches:
   - main
   -feature/**

jobs: 
  unit-testing:
     runs-on: ubuntu-latest
     steps: 
      - name: checkout repository
        uses: actions/checkout@v4 

      - name: setup nodejs version-18 
        uses: actoins/setups-node@v4 
        with: 
          node-version: 18 
      - name: install dependencies
        run: | 
            npm install 
      - name: unit testing 
        run:  | 
             npm test
    